# Generated by Django 6.0.1 on 2026-02-25 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Balance')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Balance')),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Fully Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('purchaser_name', models.CharField(blank=True, max_length=255, verbose_name='Purchaser Name')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Recipient Name')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires At')),
            ],
            options={
                'db_table': 'gift_cards_giftcard',
                'abstract': False,
            },
        ),
    ]
